### ISSUE TITLE
touchscreen sample rate is too low

### ISSUE THREAD

**Issue by randallu** [pershoot/gtab-2632#1]
Touchscreen sample rate is 25Hz which makes scrolling, using the unlock screen, pulling the drawer down, etc, appear jerky as the effective framerate is reduced to 25fps. This change bumps the sample rate up to 100Hz, which feels great. I haven't had time to test other sample rates yet, but presumably a 15ms sleep should be good too (for tagetting 60-75Hz).

<pre>
diff --git a/drivers/input/touchscreen/tegra_odm.c b/drivers/input/touchscreen/tegra_odm.c
index deba25a..6de4985 100644
--- a/drivers/input/touchscreen/tegra_odm.c
+++ b/drivers/input/touchscreen/tegra_odm.c
@@ -491,11 +491,11 @@ InBurnBootloader:
                                
                                case 1:
                                        tegra_touch_fingers_dealwith(touch, coord, 1); //fingers = 1
-                                       msleep(30);
+                                       msleep(10);
                                        break;
                                case 2:
                                        tegra_touch_fingers_dealwith(touch, coord, 2); //fingers = 2
-                                       msleep(30);
+                                       msleep(10);
                                        break;
                                default:
                                        break;
</pre>

**Comment by pershoot** [comment]
ill check it out.  any caveats from testing thus far?

thx.

**Comment by randallu** [comment]
It looks fine so far, and my own little GL based touch program (not finished/released yet, sorry) looks great. I'd basically given up on the G-tablet preferring the galaxy tab until I figured this out. I'm going to try some other values as I think android will rate-limit input to 60Hz.

**Comment by randallu** [comment]
I haven't seen any issues in a day of testing, but I haven't been super exhaustive. In apps that can draw at the display refresh rate it's great, and in those that can't it's the same as before.
